services:

  caddy:
    image: caddy:latest
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - ../config/env/caddy/.env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ../config/volumes/caddy/data:/data
      - ../config/volumes/caddy/config:/config
      - ../config/volumes/blog:/srv/blog:ro
    networks:
      - proxy

networks:
  proxy:
    external: true