services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - '8080:8080'
    volumes:
      - ../config/volumes/stirlingpdf/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ../config/volumes/stirlingpdf/extraConfigs:/configs
      - ../config/volumes/stirlingpdf/customFiles:/customFiles/
      - ../config/volumes/stirlingpdf/logs:/logs/
      - ../config/volumes/stirlingpdf/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_GB
    networks:
      - proxy
    restart: unless-stopped
networks:
  proxy:
    external: true
