services:
  nextcloud-db:
    image: postgres:15-alpine
    container_name: nextcloud-db
    restart: unless-stopped
    volumes:
      - ../config/volumes/nextcloud/db:/var/lib/postgresql/data
    env_file:
      - ../config/env/nextcloud/.env
    networks:
      - proxy

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud-db
    env_file:
      - ../config/env/nextcloud/.env
    volumes:
      - ../config/volumes/nextcloud/config:/config
      - ../config/volumes/nextcloud/data:/data
    networks:
      - proxy

networks:
  proxy:
    external: true