services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest.develium.dev
    volumes:
      - ../config/volumes/backrest/data:/data
      - ../config/volumes/backrest/config:/config
      - ../config/volumes/backrest/cache:/cache
      - ../config/volumes/backrest/tmp:/tmp
      - ../config/volumes/backrest/rclone:/root/.config/rclone # Mount for rclone config (needed when using rclone remotes)
      - /home/melissa/homelab/:/userdata  # Mount root directory to backup system
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=America/New_York
    ports:
      - "9898:9898"
    restart: unless-stopped
    networks:
      - proxy
networks:
  proxy:
    external: true