services:
  nginx:
    image: nginx:alpine
    container_name: static-web-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/share/nginx/html:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
