services:
  test-web-server:
    image: nginx:latest
    container_name: test-web-server
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - proxy
networks:
  proxy:
    external: true
