services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v3
    container_name: tinyauth
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - proxy

networks:
  proxy:
    external: true